"""create_inventory_tables

Revision ID: 80dacc493288
Revises: a2b3c4d5e6f7
Create Date: 2026-07-05 08:54:57.839391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80dacc493288'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'parent_id', name='uq_inv_category_tenant_name_parent')
    )
    op.create_index('idx_inv_categories_tenant', 'inventory_categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_categories_tenant_id'), 'inventory_categories', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_supplier_tenant_name')
    )
    op.create_index('idx_suppliers_tenant', 'suppliers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('inventory_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compatible_brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compatible_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compatible_years', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('universal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cost_price >= 0', name='check_inv_cost_non_negative'),
    sa.CheckConstraint('current_stock >= 0', name='check_inv_stock_non_negative'),
    sa.CheckConstraint('min_stock >= 0', name='check_inv_min_stock_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_products_category', 'inventory_products', ['category_id'], unique=False)
    op.create_index('idx_inv_products_low_stock', 'inventory_products', ['tenant_id'], unique=False, postgresql_where='current_stock <= min_stock AND is_active = true')
    op.create_index('idx_inv_products_sku', 'inventory_products', ['tenant_id', 'sku'], unique=True)
    op.create_index('idx_inv_products_supplier', 'inventory_products', ['supplier_id'], unique=False)
    op.create_index('idx_inv_products_tenant', 'inventory_products', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_products_tenant_id'), 'inventory_products', ['tenant_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_movements_date', 'inventory_movements', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_inv_movements_product', 'inventory_movements', ['product_id'], unique=False)
    op.create_index('idx_inv_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_inv_movements_tenant', 'inventory_movements', ['tenant_id'], unique=False)
    op.create_index('idx_inv_movements_type', 'inventory_movements', ['tenant_id', 'type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_alerts_tenant_unread', 'stock_alerts', ['tenant_id'], unique=False, postgresql_where='is_read = false')
    op.create_index(op.f('ix_stock_alerts_product_id'), 'stock_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_tenant_id'), 'stock_alerts', ['tenant_id'], unique=False)
    op.alter_column('cotizaciones', 'incidente_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Incidente vinculado (v2, cotizacion desde detalle de taller)',
               existing_nullable=True)
    op.alter_column('cotizaciones', 'monto_aceptado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Monto aceptado por el cliente al finalizar negociacion',
               existing_nullable=True)
    op.alter_column('cotizaciones', 'version',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Version del flujo: v1 (solicitud al vacio) o v2 (desde taller especifico)',
               existing_nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('cotizaciones', 'chat_sala_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a cotizacion_chat_salas (se agrega FK despues de crear la tabla)',
               existing_nullable=True)
    op.add_column('subscription_plans', sa.Column('enable_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscription_plans', sa.Column('enable_marketplace', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscription_plans', sa.Column('max_inventory_products', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('enable_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'enable_bot')
    op.drop_column('subscription_plans', 'max_inventory_products')
    op.drop_column('subscription_plans', 'enable_marketplace')
    op.drop_column('subscription_plans', 'enable_inventory')
    op.alter_column('cotizaciones', 'chat_sala_id',
               existing_type=sa.INTEGER(),
               comment='FK a cotizacion_chat_salas (se agrega FK despues de crear la tabla)',
               existing_nullable=True)
    op.alter_column('cotizaciones', 'version',
               existing_type=sa.VARCHAR(length=10),
               comment='Version del flujo: v1 (solicitud al vacio) o v2 (desde taller especifico)',
               existing_nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('cotizaciones', 'monto_aceptado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Monto aceptado por el cliente al finalizar negociacion',
               existing_nullable=True)
    op.alter_column('cotizaciones', 'incidente_id',
               existing_type=sa.INTEGER(),
               comment='Incidente vinculado (v2, cotizacion desde detalle de taller)',
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_alerts_tenant_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_product_id'), table_name='stock_alerts')
    op.drop_index('idx_stock_alerts_tenant_unread', table_name='stock_alerts', postgresql_where='is_read = false')
    op.drop_table('stock_alerts')
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index('idx_inv_movements_type', table_name='inventory_movements')
    op.drop_index('idx_inv_movements_tenant', table_name='inventory_movements')
    op.drop_index('idx_inv_movements_reference', table_name='inventory_movements')
    op.drop_index('idx_inv_movements_product', table_name='inventory_movements')
    op.drop_index('idx_inv_movements_date', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_products_tenant_id'), table_name='inventory_products')
    op.drop_index('idx_inv_products_tenant', table_name='inventory_products')
    op.drop_index('idx_inv_products_supplier', table_name='inventory_products')
    op.drop_index('idx_inv_products_sku', table_name='inventory_products')
    op.drop_index('idx_inv_products_low_stock', table_name='inventory_products', postgresql_where='current_stock <= min_stock AND is_active = true')
    op.drop_index('idx_inv_products_category', table_name='inventory_products')
    op.drop_table('inventory_products')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_index('idx_suppliers_tenant', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_inventory_categories_tenant_id'), table_name='inventory_categories')
    op.drop_index('idx_inv_categories_tenant', table_name='inventory_categories')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
