"""add_assignment_attempts_table

Revision ID: b04c970dd4e9
Revises: c2fb7174c607
Create Date: 2026-04-18 05:13:38.603554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04c970dd4e9'
down_revision: Union[str, Sequence[str], None] = 'c2fb7174c607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_location_tech_time'), table_name='technician_location_history')
    op.create_index(op.f('ix_technician_location_history_technician_id'), 'technician_location_history', ['technician_id'], unique=False)
    op.drop_index(op.f('ix_tracking_sessions_active'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_technician'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_is_active'), 'tracking_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_technician_id'), 'tracking_sessions', ['technician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_sessions_technician_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_is_active'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_technician'), 'tracking_sessions', ['technician_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_active'), 'tracking_sessions', ['is_active'], unique=False)
    op.drop_index(op.f('ix_technician_location_history_technician_id'), table_name='technician_location_history')
    op.create_index(op.f('ix_tech_location_tech_time'), 'technician_location_history', ['technician_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###
