"""add_files_table

Revision ID: bcfa17e3a088
Revises: e8b757791785
Create Date: 2026-04-09 13:03:24.315166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcfa17e3a088'
down_revision: Union[str, Sequence[str], None] = 'e8b757791785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_imagenes_uploaded_by'), table_name='vehiculos_imagenes')
    op.drop_index(op.f('ix_vehiculos_imagenes_vehiculo_id'), table_name='vehiculos_imagenes')
    op.drop_table('vehiculos_imagenes')
    op.drop_table_comment(
        'clients',
        existing_comment='Tabla de clientes. created_at y updated_at se heredan de users',
        schema=None
    )
    op.alter_column('evidencias_audios', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('evidencias_audios', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('evidencias_audios', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('evidencias_audios', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidencias_audios', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidencias_audios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_evidencias_audios_uploaded_by'), 'evidencias_audios', type_='foreignkey')
    op.create_foreign_key(None, 'evidencias_audios', 'users', ['uploaded_by'], ['id'])
    op.alter_column('evidencias_imagenes', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('evidencias_imagenes', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('evidencias_imagenes', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('evidencias_imagenes', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidencias_imagenes', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidencias_imagenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_evidencias_imagenes_uploaded_by'), 'evidencias_imagenes', type_='foreignkey')
    op.create_foreign_key(None, 'evidencias_imagenes', 'users', ['uploaded_by'], ['id'])
    op.drop_table_comment(
        'technicians',
        existing_comment='Tabla de técnicos. created_at, updated_at e is_active se heredan de users',
        schema=None
    )
    op.drop_table_comment(
        'workshops',
        existing_comment='Tabla de talleres. created_at, updated_at e is_active se heredan de users',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'workshops',
        'Tabla de talleres. created_at, updated_at e is_active se heredan de users',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'technicians',
        'Tabla de técnicos. created_at, updated_at e is_active se heredan de users',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'evidencias_imagenes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_evidencias_imagenes_uploaded_by'), 'evidencias_imagenes', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.alter_column('evidencias_imagenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evidencias_imagenes', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidencias_imagenes', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidencias_imagenes', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('evidencias_imagenes', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('evidencias_imagenes', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'evidencias_audios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_evidencias_audios_uploaded_by'), 'evidencias_audios', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.alter_column('evidencias_audios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evidencias_audios', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidencias_audios', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidencias_audios', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('evidencias_audios', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('evidencias_audios', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table_comment(
        'clients',
        'Tabla de clientes. created_at y updated_at se heredan de users',
        existing_comment=None,
        schema=None
    )
    op.create_table('vehiculos_imagenes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('es_principal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_vehiculos_imagenes_uploaded_by'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], name=op.f('fk_vehiculos_imagenes_vehiculo_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vehiculos_imagenes_pkey'))
    )
    op.create_index(op.f('ix_vehiculos_imagenes_vehiculo_id'), 'vehiculos_imagenes', ['vehiculo_id'], unique=False)
    op.create_index(op.f('ix_vehiculos_imagenes_uploaded_by'), 'vehiculos_imagenes', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###
