"""Initial migration from models

Revision ID: d7a646680674
Revises: 
Create Date: 2026-04-06 10:22:33.449118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a646680674'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comision', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_especialidades_nombre'), 'especialidades', ['nombre'], unique=True)
    op.create_table('estados_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_servicio_nombre'), 'estados_servicio', ['nombre'], unique=True)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("user_type IN ('client', 'workshop', 'technician', 'admin')", name='check_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_blocked_until'), 'users', ['blocked_until'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ci', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_ci'), 'clients', ['ci'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('locked_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_categoria_id'), 'servicios', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_servicios_nombre'), 'servicios', ['nombre'], unique=False)
    op.create_table('two_factor_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_auth_user_id'), 'two_factor_auth', ['user_id'], unique=True)
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workshop_phone', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('coverage_radius_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('coverage_radius_km >= 0', name='check_coverage_radius_positive'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshops_is_available'), 'workshops', ['is_available'], unique=False)
    op.create_index(op.f('ix_workshops_latitude'), 'workshops', ['latitude'], unique=False)
    op.create_index(op.f('ix_workshops_longitude'), 'workshops', ['longitude'], unique=False)
    op.create_index(op.f('ix_workshops_workshop_name'), 'workshops', ['workshop_name'], unique=False)
    op.create_table('servicios_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('precio >= 0', name='check_precio_positive'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taller_id', 'servicio_id', name='uq_taller_servicio')
    )
    op.create_index(op.f('ix_servicios_taller_servicio_id'), 'servicios_taller', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_servicios_taller_taller_id'), 'servicios_taller', ['taller_id'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technicians_is_available'), 'technicians', ['is_available'], unique=False)
    op.create_index(op.f('ix_technicians_workshop_id'), 'technicians', ['workshop_id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anio > 1900', name='check_anio_valid'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_client_id'), 'vehiculos', ['client_id'], unique=False)
    op.create_index(op.f('ix_vehiculos_matricula'), 'vehiculos', ['matricula'], unique=True)
    op.create_table('workshop_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='check_day_of_week_range'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'day_of_week', name='uq_workshop_day')
    )
    op.create_index(op.f('ix_workshop_schedules_day_of_week'), 'workshop_schedules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_workshop_schedules_workshop_id'), 'workshop_schedules', ['workshop_id'], unique=False)
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('direccion_referencia', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria_ia', sa.String(length=100), nullable=True),
    sa.Column('prioridad_ia', sa.String(length=20), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('es_ambiguo', sa.Boolean(), nullable=False),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado_actual IN ('pendiente', 'asignado', 'en_proceso', 'resuelto', 'cancelado')", name='check_estado_actual_valid'),
    sa.CheckConstraint("prioridad_ia IN ('alta', 'media', 'baja') OR prioridad_ia IS NULL", name='check_prioridad_ia_valid'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['workshops.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentes_client_id'), 'incidentes', ['client_id'], unique=False)
    op.create_index(op.f('ix_incidentes_created_at'), 'incidentes', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidentes_estado_actual'), 'incidentes', ['estado_actual'], unique=False)
    op.create_index(op.f('ix_incidentes_latitude'), 'incidentes', ['latitude'], unique=False)
    op.create_index(op.f('ix_incidentes_longitude'), 'incidentes', ['longitude'], unique=False)
    op.create_index(op.f('ix_incidentes_taller_id'), 'incidentes', ['taller_id'], unique=False)
    op.create_index(op.f('ix_incidentes_tecnico_id'), 'incidentes', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_incidentes_vehiculo_id'), 'incidentes', ['vehiculo_id'], unique=False)
    op.create_table('technician_especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'especialidad_id', name='uq_technician_especialidad')
    )
    op.create_index(op.f('ix_technician_especialidades_especialidad_id'), 'technician_especialidades', ['especialidad_id'], unique=False)
    op.create_index(op.f('ix_technician_especialidades_technician_id'), 'technician_especialidades', ['technician_id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('TEXT', 'IMAGE', 'AUDIO')", name='check_tipo_evidencia_valid'),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_incidente_id'), 'evidencias', ['incidente_id'], unique=False)
    op.create_index(op.f('ix_evidencias_tipo'), 'evidencias', ['tipo'], unique=False)
    op.create_table('historial_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_servicio.id'], ),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_servicio_estado_id'), 'historial_servicio', ['estado_id'], unique=False)
    op.create_index(op.f('ix_historial_servicio_fecha'), 'historial_servicio', ['fecha'], unique=False)
    op.create_index(op.f('ix_historial_servicio_incidente_id'), 'historial_servicio', ['incidente_id'], unique=False)
    op.create_table('evidencias_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidencia_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_audios_evidencia_id'), 'evidencias_audios', ['evidencia_id'], unique=False)
    op.create_table('evidencias_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidencia_id', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_imagenes_evidencia_id'), 'evidencias_imagenes', ['evidencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidencias_imagenes_evidencia_id'), table_name='evidencias_imagenes')
    op.drop_table('evidencias_imagenes')
    op.drop_index(op.f('ix_evidencias_audios_evidencia_id'), table_name='evidencias_audios')
    op.drop_table('evidencias_audios')
    op.drop_index(op.f('ix_historial_servicio_incidente_id'), table_name='historial_servicio')
    op.drop_index(op.f('ix_historial_servicio_fecha'), table_name='historial_servicio')
    op.drop_index(op.f('ix_historial_servicio_estado_id'), table_name='historial_servicio')
    op.drop_table('historial_servicio')
    op.drop_index(op.f('ix_evidencias_tipo'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_incidente_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_technician_especialidades_technician_id'), table_name='technician_especialidades')
    op.drop_index(op.f('ix_technician_especialidades_especialidad_id'), table_name='technician_especialidades')
    op.drop_table('technician_especialidades')
    op.drop_index(op.f('ix_incidentes_vehiculo_id'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_tecnico_id'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_taller_id'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_longitude'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_latitude'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_estado_actual'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_created_at'), table_name='incidentes')
    op.drop_index(op.f('ix_incidentes_client_id'), table_name='incidentes')
    op.drop_table('incidentes')
    op.drop_index(op.f('ix_workshop_schedules_workshop_id'), table_name='workshop_schedules')
    op.drop_index(op.f('ix_workshop_schedules_day_of_week'), table_name='workshop_schedules')
    op.drop_table('workshop_schedules')
    op.drop_index(op.f('ix_vehiculos_matricula'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_client_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_technicians_workshop_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_is_available'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_servicios_taller_taller_id'), table_name='servicios_taller')
    op.drop_index(op.f('ix_servicios_taller_servicio_id'), table_name='servicios_taller')
    op.drop_table('servicios_taller')
    op.drop_index(op.f('ix_workshops_workshop_name'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_longitude'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_latitude'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_is_available'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_two_factor_auth_user_id'), table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    op.drop_index(op.f('ix_servicios_nombre'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_categoria_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_clients_ci'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('administrators')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_blocked_until'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_estados_servicio_nombre'), table_name='estados_servicio')
    op.drop_table('estados_servicio')
    op.drop_index(op.f('ix_especialidades_nombre'), table_name='especialidades')
    op.drop_table('especialidades')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
