"""add_cotizaciones_y_cotizacion_respuestas

Revision ID: d8fa9b0b655b
Revises: c9d0e1f2a3b4
Create Date: 2026-06-07 15:14:54.699217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8fa9b0b655b'
down_revision: Union[str, Sequence[str], None] = 'c9d0e1f2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_entity'), table_name='files')
    op.drop_index(op.f('idx_uploaded_by'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_cancellation_requests_incident_id'), table_name='cancellation_requests')
    op.create_index(op.f('ix_cancellation_requests_incident_id'), 'cancellation_requests', ['incident_id'], unique=False)
    op.drop_index(op.f('idx_incidentes_assignment_mode'), table_name='incidentes')
    op.create_index(op.f('ix_incidentes_assignment_mode'), 'incidentes', ['assignment_mode'], unique=False)
    op.alter_column('outbox_events', 'ws_immediate_sent',
               existing_type=sa.BOOLEAN(),
               comment='Whether immediate WebSocket was already sent by EventPublisher',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'usd'::character varying"))
    op.create_index(op.f('ix_subscription_invoices_id'), 'subscription_invoices', ['id'], unique=False)
    op.alter_column('subscription_plans', 'max_technicians',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('subscription_plans', 'max_services',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('subscription_plans', 'enable_kpis',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_reports',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_realtime_tracking',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_quotes',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_voice_reports',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('subscription_plans', 'enable_priority_support',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_api_access',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_white_label',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.alter_column('sync_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_operations', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenant_subscriptions', 'payment_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'stripe'::character varying"))
    op.create_index(op.f('ix_tenant_subscriptions_id'), 'tenant_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.drop_index(op.f('ix_workshops_nit'), table_name='workshops')
    op.create_unique_constraint(None, 'workshops', ['nit'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshops', type_='unique')
    op.create_index(op.f('ix_workshops_nit'), 'workshops', ['nit'], unique=True)
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenant_subscriptions_id'), table_name='tenant_subscriptions')
    op.alter_column('tenant_subscriptions', 'payment_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'stripe'::character varying"))
    op.alter_column('tenant_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sync_operations', 'processed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sync_operations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_operations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('subscription_plans', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subscription_plans', 'enable_white_label',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_api_access',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_priority_support',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_voice_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('subscription_plans', 'enable_quotes',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_realtime_tracking',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'enable_kpis',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscription_plans', 'max_services',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('subscription_plans', 'max_technicians',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.drop_index(op.f('ix_subscription_invoices_id'), table_name='subscription_invoices')
    op.alter_column('subscription_invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'usd'::character varying"))
    op.alter_column('outbox_events', 'ws_immediate_sent',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether immediate WebSocket was already sent by EventPublisher',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_incidentes_assignment_mode'), table_name='incidentes')
    op.create_index(op.f('idx_incidentes_assignment_mode'), 'incidentes', ['assignment_mode'], unique=False)
    op.drop_index(op.f('ix_cancellation_requests_incident_id'), table_name='cancellation_requests')
    op.create_index(op.f('ix_cancellation_requests_incident_id'), 'cancellation_requests', ['incident_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey')),
    sa.UniqueConstraint('file_path', name=op.f('files_file_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('idx_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_entity'), 'files', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
