"""recreate_missing_indexes

Revision ID: e922011468f0
Revises: f9e8d7c6b5a4
Create Date: 2026-04-23 00:11:47.653647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e922011468f0'
down_revision: Union[str, Sequence[str], None] = 'f9e8d7c6b5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assignment_attempts_incident_created'), table_name='assignment_attempts')
    op.drop_index(op.f('idx_assignment_attempts_pending'), table_name='assignment_attempts', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_assignment_attempts_workshop_status'), table_name='assignment_attempts')
    op.drop_constraint(op.f('cancellation_requests_incident_id_key'), 'cancellation_requests', type_='unique')
    op.drop_index(op.f('ix_cancellation_requests_incident_id'), table_name='cancellation_requests')
    op.create_index(op.f('ix_cancellation_requests_incident_id'), 'cancellation_requests', ['incident_id'], unique=True)
    op.drop_constraint(op.f('conversations_workshop_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_incident_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_client_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'incidentes', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'workshops', ['workshop_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'clients', ['client_id'], ['id'])
    op.alter_column('event_log', 'event_id',
               existing_type=sa.UUID(),
               comment='UUID of the original event',
               existing_nullable=False)
    op.alter_column('event_log', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Type of event (e.g., 'incident.created')",
               existing_nullable=False)
    op.alter_column('event_log', 'payload',
               existing_type=sa.TEXT(),
               comment='JSON payload of the event',
               existing_nullable=False)
    op.alter_column('event_log', 'delivered_via',
               existing_type=sa.VARCHAR(length=20),
               comment='Delivery method: websocket, fcm, or both',
               existing_nullable=False)
    op.alter_column('event_log', 'delivered_to',
               existing_type=sa.INTEGER(),
               comment='User ID who received the event',
               existing_nullable=False)
    op.alter_column('event_log', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When event was delivered',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_event_log_event_id', 'event_log', ['event_id'], unique=False)
    op.drop_table_comment(
        'event_log',
        existing_comment='Log of all delivered events for recovery and analytics',
        schema=None
    )
    op.drop_index(op.f('idx_incidentes_client_fecha'), table_name='incidentes')
    op.drop_index(op.f('idx_incidentes_estado_fecha'), table_name='incidentes', postgresql_where="((estado_actual)::text = ANY ((ARRAY['pendiente'::character varying, 'asignado'::character varying, 'aceptado'::character varying, 'en_camino'::character varying, 'en_proceso'::character varying])::text[]))")
    op.drop_index(op.f('idx_incidentes_taller_estado'), table_name='incidentes', postgresql_where='(taller_id IS NOT NULL)')
    op.drop_index(op.f('idx_incidentes_tecnico_estado'), table_name='incidentes', postgresql_where='(tecnico_id IS NOT NULL)')
    op.drop_index(op.f('idx_messages_incident_created'), table_name='messages')
    op.drop_index(op.f('idx_messages_unread'), table_name='messages', postgresql_where='(is_read = false)')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_incident_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'incidentes', ['incident_id'], ['id'])
    op.drop_index(op.f('idx_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.alter_column('outbox_events', 'event_id',
               existing_type=sa.UUID(),
               comment='Unique identifier for deduplication',
               existing_nullable=False)
    op.alter_column('outbox_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Type of event (e.g., 'incident.created')",
               existing_nullable=False)
    op.alter_column('outbox_events', 'payload',
               existing_type=sa.TEXT(),
               comment='JSON payload of the event',
               existing_nullable=False)
    op.alter_column('outbox_events', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment='Schema version for evolution',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('outbox_events', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='event_priority'),
               comment='Processing priority',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::event_priority"))
    op.alter_column('outbox_events', 'processed',
               existing_type=sa.BOOLEAN(),
               comment='Whether event has been processed',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('outbox_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When event was processed',
               existing_nullable=True)
    op.alter_column('outbox_events', 'retry_count',
               existing_type=sa.INTEGER(),
               comment='Number of processing attempts',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('outbox_events', 'last_error',
               existing_type=sa.TEXT(),
               comment='Last error message if processing failed',
               existing_nullable=True)
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When event was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'outbox_events',
        existing_comment='Outbox events for transactional event publishing',
        schema=None
    )
    op.drop_index(op.f('idx_tech_location_history_tech_recorded'), table_name='technician_location_history')
    op.drop_index(op.f('idx_tracking_sessions_active'), table_name='tracking_sessions', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_tracking_sessions_incident_started'), table_name='tracking_sessions', postgresql_where='(incidente_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tracking_sessions_incident_started'), 'tracking_sessions', ['incidente_id', sa.literal_column('started_at DESC')], unique=False, postgresql_where='(incidente_id IS NOT NULL)')
    op.create_index(op.f('idx_tracking_sessions_active'), 'tracking_sessions', ['is_active', 'started_at'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_tech_location_history_tech_recorded'), 'technician_location_history', ['technician_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table_comment(
        'outbox_events',
        'Outbox events for transactional event publishing',
        existing_comment=None,
        schema=None
    )
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When event was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbox_events', 'last_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Last error message if processing failed',
               existing_nullable=True)
    op.alter_column('outbox_events', 'retry_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of processing attempts',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('outbox_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When event was processed',
               existing_nullable=True)
    op.alter_column('outbox_events', 'processed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether event has been processed',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('outbox_events', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='event_priority'),
               comment=None,
               existing_comment='Processing priority',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::event_priority"))
    op.alter_column('outbox_events', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Schema version for evolution',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('outbox_events', 'payload',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON payload of the event',
               existing_nullable=False)
    op.alter_column('outbox_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Type of event (e.g., 'incident.created')",
               existing_nullable=False)
    op.alter_column('outbox_events', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for deduplication',
               existing_nullable=False)
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_incident_id_fkey'), 'messages', 'incidentes', ['incident_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_messages_unread'), 'messages', ['is_read', 'created_at'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_messages_incident_created'), 'messages', ['incident_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_incidentes_tecnico_estado'), 'incidentes', ['tecnico_id', 'estado_actual'], unique=False, postgresql_where='(tecnico_id IS NOT NULL)')
    op.create_index(op.f('idx_incidentes_taller_estado'), 'incidentes', ['taller_id', 'estado_actual'], unique=False, postgresql_where='(taller_id IS NOT NULL)')
    op.create_index(op.f('idx_incidentes_estado_fecha'), 'incidentes', ['estado_actual', sa.literal_column('created_at DESC')], unique=False, postgresql_where="((estado_actual)::text = ANY ((ARRAY['pendiente'::character varying, 'asignado'::character varying, 'aceptado'::character varying, 'en_camino'::character varying, 'en_proceso'::character varying])::text[]))")
    op.create_index(op.f('idx_incidentes_client_fecha'), 'incidentes', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table_comment(
        'event_log',
        'Log of all delivered events for recovery and analytics',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_event_log_event_id', table_name='event_log')
    op.alter_column('event_log', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When event was delivered',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_log', 'delivered_to',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID who received the event',
               existing_nullable=False)
    op.alter_column('event_log', 'delivered_via',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Delivery method: websocket, fcm, or both',
               existing_nullable=False)
    op.alter_column('event_log', 'payload',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON payload of the event',
               existing_nullable=False)
    op.alter_column('event_log', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Type of event (e.g., 'incident.created')",
               existing_nullable=False)
    op.alter_column('event_log', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID of the original event',
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_client_id_fkey'), 'conversations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_incident_id_fkey'), 'conversations', 'incidentes', ['incident_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_workshop_id_fkey'), 'conversations', 'workshops', ['workshop_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_cancellation_requests_incident_id'), table_name='cancellation_requests')
    op.create_index(op.f('ix_cancellation_requests_incident_id'), 'cancellation_requests', ['incident_id'], unique=False)
    op.create_unique_constraint(op.f('cancellation_requests_incident_id_key'), 'cancellation_requests', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_assignment_attempts_workshop_status'), 'assignment_attempts', ['workshop_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_assignment_attempts_pending'), 'assignment_attempts', ['status', 'attempted_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('idx_assignment_attempts_incident_created'), 'assignment_attempts', ['incident_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
