"""add_assignment_attempts_table_fixed

Revision ID: ed64a62f1f1b
Revises: b04c970dd4e9
Create Date: 2026-04-18 05:15:04.949945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed64a62f1f1b'
down_revision: Union[str, Sequence[str], None] = 'b04c970dd4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('algorithmic_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('assignment_strategy', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_attempts_attempted_at'), 'assignment_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_assignment_attempts_incident_id'), 'assignment_attempts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_assignment_attempts_technician_id'), 'assignment_attempts', ['technician_id'], unique=False)
    op.create_index(op.f('ix_assignment_attempts_workshop_id'), 'assignment_attempts', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_attempts_workshop_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_technician_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_incident_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_attempted_at'), table_name='assignment_attempts')
    op.drop_table('assignment_attempts')
    # ### end Alembic commands ###
